ANCHORS:
 node_steps: &node_steps
   steps:
     - checkout
     - run: npm ci
     - run: npm run lint
     - run: npm test
     # Check whether "run build" is successful
     - run: npm run build

version: 2
jobs:
  node_14:
    docker:
      - image: circleci/node:14
    <<: *node_steps
  node_12:
    docker:
      - image: circleci/node:12
    <<: *node_steps
  node_10:
    docker:
      - image: circleci/node:10
    <<: *node_steps

workflows:
  version: 2
  node_tests:
    jobs:
      - node_14:
          filters:
            tags:
              only: /.*/
      - node_12:
          filters:
            tags:
              only: /.*/
      - node_10:
          filters:
            tags:
              only: /.*/
